name: moldedbits
description: blog
tagline: on mobile, code and 42
meta_description: "moldedbits Blog"

highlighter: rouge
logo: false
paginate: 15
baseurl: 'http://eng.moldedbits.com/'
domain_name: 'eng.moldedbits.com'
google_analytics: 'UA-92344727-4'

# Details for the RSS feed generator
url:            'http://eng.moldedbits.com'
author:         'Anuj Middha'
plugins: [jekyll-paginate]
